### ISSUE TITLE
Close GitHub Discussions and merge it to GitHub Issues

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1666]
I have opened GitHub Discussions, but I think we should close GitHub Discussions and merge it to GitHub Issues.

* Discussion can't be closed, so the status of Discussion is unclear
* Issues is dispersed between GitHub Issues and Discussions. We should gather issues into one place

## Task

- [x] Transfer some Discussion to Issues
  - [x] https://github.com/aquaproj/aqua/issues/1673
  - [x] https://github.com/aquaproj/aqua/issues/1671
  - [x] https://github.com/aquaproj/aqua/issues/1670
  - [x] https://github.com/aquaproj/aqua/issues/1672
- [x] Fix the document. Fix the link to Discussion https://github.com/aquaproj/aquaproj.github.io/pull/281
- [x] Disable GitHub Discussions
  - [x] org
  - [x] aqua

**Comment by suzuki-shunsuke** [comment]
Done.

**Comment by suzuki-shunsuke** [comment]
> Discussion can't be closed, so the status of Discussion is unclear

Discussion can be closed now.

**Comment by suzuki-shunsuke** [comment]
I changed the mind and reopened Discussions.

- https://github.com/aquaproj/aqua/issues/1930
